# Site settings
title: Choss Bucket
# email: your-email@domain.com
description: Just some climbing in Europe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chossBucket
github_username:  chossBucket

# Build settings
markdown: kramdown


# Markdown Processors
kramdown:
  input: GFM
